---
title: "fano experiment"
output: html_document
date: "2023-07-20"
---

```{r}
rm(list=ls())
library("nnet")
safety <- read.csv("train2.csv")
str(safety)
summary(safety)
```

```{r}
safety1 <- subset(safety, select=-c(segment, year, miles, milesind, night, nightind, ppark, gender, age, ageind, educ, region, Urb, income, incomeind, CC4, GN4, NS4, BU4, FA4, LD4, BZ4, FC4, FP4, RP4, PP4, KA4, SC4, TS4, NV4, MA4, LB4, AF4, HU4, Price4, Ch1, Ch2, Ch3, Ch4, Case, No, Task))
```


```{r}
set.seed(123)
Model=nnet(Choice~.,data=safety1,size=5,linout=T)

```

```{r}
Model$value
sum((safety1$Choice-mean(safety1$Choice))^2)
```

```{r}
rescaled.safety <- scale(safety1)

set.seed(123)
best.rss <- 20000
for(i in 1:25){
  nnmdl <- nnet(Choice ~., 
                data=rescaled.safety, size=6, linout=T, trace=F)
  best.rss[i]=nnmdl$value
}
min(best.rss)
```
```{r}
summary(rescaled.safety)
```


```{r}
which.min(best.rss)
```

```{r}
plot(sort(best.rss)) 
```
```{r}
sort(best.rss)
```

```{r}
set.seed(25374)
best.rss=NULL
bestrss <- 20000
for(i in 1:25){
  nnmdl <- nnet(Choice ~., data=rescaled.safety, size=6, linout=T, trace=F)
  best.rss[i]=nnmdl$value
  if(nnmdl$value < bestrss){
     bestnn <- nnmdl
     bestrss <- nnmdl$value
   }
}
min(best.rss)
```

```{r}
summary(bestnn)
```

```{r}
test <- read.csv("test1.csv")

MrChoice <-sample(c(1,2,3,4),nrow(test),replace=TRUE, prob = c(0.25, 0.25, 0.25,0.25))
test$Choice<-MrChoice
table(test$Choice)
S1 <- subset(test, select=-c(segment, year, miles, milesind, night, nightind, ppark, gender, age, ageind, educ, region, Urb, income, incomeind, CC4, GN4, NS4, BU4, FA4, LD4, BZ4, FC4, FP4, RP4, PP4, KA4, SC4, TS4, NV4, MA4, LB4, AF4, HU4, Price4, Ch1, Ch2, Ch3, Ch4, Case, No, Task))
head(S1)
P1 <- predict(bestnn, newdata=S1, type="raw")
PredictedTest <- apply(P1,1,which.max)
table(PredictedTest)
```
